/*
 __  __                  _               _               _ 
|  \/  | ___  __ _  __ _| |__   __ _ ___| |_ ___ _ __ __| |
| |\/| |/ _ \/ _` |/ _` | '_ \ / _` / __| __/ _ \ '__/ _` |
| |  | |  __/ (_| | (_| | |_) | (_| \__ \ ||  __/ | | (_| |
|_|  |_|\___|\__, |\__,_|_.__/ \__,_|___/\__\___|_|  \__,_|
             |___/                                         
© Perpetrated by tonikelope since 2016
 */
package com.tonikelope.megabasterd;

import javax.sound.midi.Sequencer;
import javax.swing.*;
import java.awt.*;
import java.util.logging.Logger;

import static com.tonikelope.megabasterd.MainPanel.THREAD_POOL;
import static com.tonikelope.megabasterd.MainPanel.VERSION;
import static com.tonikelope.megabasterd.MiscTools.checkNewVersion;
import static com.tonikelope.megabasterd.MiscTools.openBrowserURL;

/**
 * @author tonikelope
 */
public class AboutDialog extends javax.swing.JDialog {

    public static final String MEGA_URL = "https://mega.nz/";
    public static final String MEGABASTERD_URL = "https://github.com/tonikelope/megabasterd/releases/latest";
    public static final String TONIKELOPE_URL = "https://github.com/tonikelope/";
    public static final String MEGACRYPTER_URL = "https://tonikelope.github.io/megacrypter/";
    public static final String SPAIN_URL = "https://en.wikipedia.org/wiki/Spain";
    public static final String MEGABASTERD_GITHUB_URL = "https://tonikelope.github.io/megabasterd/";
    public static final String KIM_URL = "http://www.kim.com/";
    private static volatile Sequencer _midi = null;

    public AboutDialog(final MainPanelView parent, final boolean modal) {

        super(parent, modal);

        MiscTools.GUIRunAndWait(() -> {
            this.initComponents();

//            updateFonts(this, GUI_FONT, parent.getMain_panel().getZoom_factor());
//
//            translateLabels(this);

            if (MainPanel.getNew_version() != null) {
                this.mcdown_url_button.setEnabled(true);
            }

            this.pack();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.title_label = new javax.swing.JLabel();
        this.made_in_spain_label = new javax.swing.JLabel();
        this.subtitle_label = new javax.swing.JLabel();
        this.mc_logo_label = new javax.swing.JLabel();
        this.mcdown_url_button = new javax.swing.JButton();
        this.author_webpage_label = new javax.swing.JLabel();
        this.mb_label = new javax.swing.JLabel();
        this.check_version_button = new javax.swing.JButton();
        this.dot_com_label = new javax.swing.JLabel();
        this.java_version = new javax.swing.JLabel();
        this.jPanel1 = new javax.swing.JPanel();
        this.jLabel5 = new javax.swing.JLabel();
        this.jLabel2 = new javax.swing.JLabel();
        this.jLabel3 = new javax.swing.JLabel();
        this.jLabel1 = new javax.swing.JLabel();
        this.jLabel4 = new javax.swing.JLabel();
        this.jLabel6 = new javax.swing.JLabel();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setTitle("About");
        this.setIconImage(null);
        this.setResizable(false);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(final java.awt.event.WindowEvent evt) {
                AboutDialog.this.formWindowClosing(evt);
            }

            @Override
            public void windowOpened(final java.awt.event.WindowEvent evt) {
                AboutDialog.this.formWindowOpened(evt);
            }
        });

        this.title_label.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        this.title_label.setText("MegaBasterd " + VERSION + " ");
        this.title_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.title_label.setDoubleBuffered(true);
        this.title_label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.title_labelMouseReleased(evt);
            }

            @Override
            public void mouseExited(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.title_labelMouseExited(evt);
            }

            @Override
            public void mouseEntered(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.title_labelMouseEntered(evt);
            }
        });

        this.made_in_spain_label.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/m_in_spain.png"))); // NOI18N
        this.made_in_spain_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.made_in_spain_label.setDoubleBuffered(true);
        this.made_in_spain_label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.made_in_spain_labelMouseReleased(evt);
            }
        });

        this.subtitle_label.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        this.subtitle_label.setForeground(new java.awt.Color(102, 102, 102));
        this.subtitle_label.setText("Yet another unofficial (and ugly) cross-platform MEGA downloader/uploader/streaming suite.");
        this.subtitle_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.subtitle_label.setDoubleBuffered(true);
        this.subtitle_label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.subtitle_labelMouseReleased(evt);
            }

            @Override
            public void mouseExited(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.subtitle_labelMouseExited(evt);
            }

            @Override
            public void mouseEntered(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.subtitle_labelMouseEntered(evt);
            }
        });

        this.mc_logo_label.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/mega_crypter.png"))); // NOI18N
        this.mc_logo_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.mc_logo_label.setDoubleBuffered(true);
        this.mc_logo_label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.mc_logo_labelMouseReleased(evt);
            }
        });

        this.mcdown_url_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        this.mcdown_url_button.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/icons8-copy-to-clipboard-30.png"))); // NOI18N
        this.mcdown_url_button.setText("Download latest version");
        this.mcdown_url_button.setDoubleBuffered(true);
        this.mcdown_url_button.setEnabled(false);
        this.mcdown_url_button.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                AboutDialog.this.mcdown_url_buttonActionPerformed(evt);
            }
        });

        this.author_webpage_label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        this.author_webpage_label.setForeground(new java.awt.Color(102, 102, 102));
        this.author_webpage_label.setText("Made with love (and with no warranty) by tonikelope.");
        this.author_webpage_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.author_webpage_label.setDoubleBuffered(true);
        this.author_webpage_label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.author_webpage_labelMouseEntered(evt);
            }

            @Override
            public void mouseExited(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.author_webpage_labelMouseExited(evt);
            }

            @Override
            public void mouseReleased(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.author_webpage_labelMouseReleased(evt);
            }
        });

        this.mb_label.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/mbasterd_logo_nuevo.png"))); // NOI18N
        this.mb_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.mb_label.setDoubleBuffered(true);
        this.mb_label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.mb_labelMouseReleased(evt);
            }
        });

        this.check_version_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        this.check_version_button.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/icons8-restart-30.png"))); // NOI18N
        this.check_version_button.setText("Check version");
        this.check_version_button.setDoubleBuffered(true);
        this.check_version_button.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                AboutDialog.this.check_version_buttonActionPerformed(evt);
            }
        });

        this.dot_com_label.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/dot_com2.png"))); // NOI18N
        this.dot_com_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.dot_com_label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(final java.awt.event.MouseEvent evt) {
                AboutDialog.this.dot_com_labelMouseReleased(evt);
            }
        });

        this.java_version.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        this.java_version.setForeground(new java.awt.Color(102, 102, 102));
        this.java_version.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        this.java_version.setText(System.getProperty("java.vm.name") + " " + System.getProperty("java.version"));

        this.jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        this.jLabel5.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/flags/turkey.png"))); // NOI18N
        this.jLabel5.setText("FabrieI");

        this.jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        this.jLabel2.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/flags/germany.png"))); // NOI18N
        this.jLabel2.setText("NieckLikesCode");

        this.jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        this.jLabel3.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/flags/hungary.png"))); // NOI18N
        this.jLabel3.setText("Roschach96 ");

        this.jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        this.jLabel1.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/flags/china.png"))); // NOI18N
        this.jLabel1.setText("linkea131");
        this.jLabel1.setDoubleBuffered(true);

        this.jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        this.jLabel4.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/flags/italy.png"))); // NOI18N
        this.jLabel4.setText("bovirus ");

        this.jLabel6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        this.jLabel6.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/flags/vietnam.png"))); // NOI18N
        this.jLabel6.setText("rattybox");

        final javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(this.jPanel1);
        this.jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(this.jLabel1)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(this.jLabel2)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(this.jLabel3)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(this.jLabel4)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(this.jLabel5)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(this.jLabel6)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(this.jLabel1)
                                        .addComponent(this.jLabel2)
                                        .addComponent(this.jLabel3)
                                        .addComponent(this.jLabel4)
                                        .addComponent(this.jLabel5)
                                        .addComponent(this.jLabel6))
                                .addContainerGap())
        );

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
        this.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(this.jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(this.subtitle_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(this.title_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(this.mcdown_url_button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(this.check_version_button))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(this.made_in_spain_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(this.dot_com_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(this.mb_label)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(this.mc_logo_label))
                                                        .addComponent(this.author_webpage_label, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(this.java_version, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(this.title_label)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(this.mcdown_url_button)
                                                        .addComponent(this.check_version_button))))
                                .addGap(18, 18, 18)
                                .addComponent(this.subtitle_label)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(this.made_in_spain_label)
                                        .addComponent(this.dot_com_label)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(this.mb_label)
                                                        .addComponent(this.mc_logo_label))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(this.author_webpage_label)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(this.java_version)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(this.jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        this.pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mcdown_url_buttonActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcdown_url_buttonActionPerformed

        openBrowserURL(MEGABASTERD_URL);
    }//GEN-LAST:event_mcdown_url_buttonActionPerformed

    private void check_version_buttonActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_version_buttonActionPerformed

        final String old_check_version_button_text = this.check_version_button.getText();

        this.check_version_button.setEnabled(false);

        this.check_version_button.setText(LabelTranslatorSingleton.getInstance().translate("Checking, please wait..."));

        this.pack();

        final Dialog tthis = this;

        THREAD_POOL.execute(() -> {
            final String new_version = checkNewVersion(MEGABASTERD_URL);

            MiscTools.GUIRun(() -> {
                if (new_version != null) {

                    JOptionPane.showMessageDialog(tthis, LabelTranslatorSingleton.getInstance().translate("MegaBasterd NEW VERSION is available! -> ") + new_version);

                    this.mcdown_url_button.setEnabled(true);

                } else {

                    JOptionPane.showMessageDialog(tthis, LabelTranslatorSingleton.getInstance().translate("You have the latest version ;)"));

                    this.mcdown_url_button.setEnabled(false);
                }

                this.check_version_button.setText(old_check_version_button_text);

                this.check_version_button.setEnabled(true);

                this.pack();
            });
        });
    }//GEN-LAST:event_check_version_buttonActionPerformed

    private void mb_labelMouseReleased(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mb_labelMouseReleased

        openBrowserURL(MEGABASTERD_GITHUB_URL);
    }//GEN-LAST:event_mb_labelMouseReleased

    private void author_webpage_labelMouseReleased(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_author_webpage_labelMouseReleased

        openBrowserURL(TONIKELOPE_URL);
    }//GEN-LAST:event_author_webpage_labelMouseReleased

    private void mc_logo_labelMouseReleased(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mc_logo_labelMouseReleased

        openBrowserURL(MEGACRYPTER_URL);
    }//GEN-LAST:event_mc_logo_labelMouseReleased

    private void made_in_spain_labelMouseReleased(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_made_in_spain_labelMouseReleased

        openBrowserURL(SPAIN_URL);
    }//GEN-LAST:event_made_in_spain_labelMouseReleased

    private void title_labelMouseReleased(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title_labelMouseReleased
        openBrowserURL(MEGABASTERD_GITHUB_URL);
    }//GEN-LAST:event_title_labelMouseReleased

    private void author_webpage_labelMouseEntered(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_author_webpage_labelMouseEntered
        this.author_webpage_label.setForeground(Color.blue);
    }//GEN-LAST:event_author_webpage_labelMouseEntered

    private void author_webpage_labelMouseExited(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_author_webpage_labelMouseExited
        this.author_webpage_label.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_author_webpage_labelMouseExited

    private void title_labelMouseEntered(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title_labelMouseEntered
        this.title_label.setForeground(Color.blue);
    }//GEN-LAST:event_title_labelMouseEntered

    private void title_labelMouseExited(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title_labelMouseExited
        this.title_label.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_title_labelMouseExited

    private void subtitle_labelMouseReleased(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtitle_labelMouseReleased
        // TODO add your handling code here:
        openBrowserURL(MEGA_URL);
    }//GEN-LAST:event_subtitle_labelMouseReleased

    private void dot_com_labelMouseReleased(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dot_com_labelMouseReleased
        // TODO add your handling code here:
        openBrowserURL(KIM_URL);
    }//GEN-LAST:event_dot_com_labelMouseReleased

    private void subtitle_labelMouseEntered(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtitle_labelMouseEntered
        // TODO add your handling code here:
        this.subtitle_label.setForeground(Color.blue);
    }//GEN-LAST:event_subtitle_labelMouseEntered

    private void subtitle_labelMouseExited(final java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtitle_labelMouseExited
        // TODO add your handling code here:
        this.subtitle_label.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_subtitle_labelMouseExited

    private void formWindowOpened(final java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        THREAD_POOL.execute(() -> {

            if (_midi == null) {
                _midi = MiscTools.midiLoopPlay("/midis/a-team.mid", 70);
            } else {
                _midi.start();
            }
        });
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(final java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        THREAD_POOL.execute(() -> {
            _midi.stop();
        });
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author_webpage_label;
    private javax.swing.JButton check_version_button;
    private javax.swing.JLabel dot_com_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel java_version;
    private javax.swing.JLabel made_in_spain_label;
    private javax.swing.JLabel mb_label;
    private javax.swing.JLabel mc_logo_label;
    private javax.swing.JButton mcdown_url_button;
    private javax.swing.JLabel subtitle_label;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(AboutDialog.class.getName());
}
