/*
 __  __                  _               _               _ 
|  \/  | ___  __ _  __ _| |__   __ _ ___| |_ ___ _ __ __| |
| |\/| |/ _ \/ _` |/ _` | '_ \ / _` / __| __/ _ \ '__/ _` |
| |  | |  __/ (_| | (_| | |_) | (_| \__ \ ||  __/ | | (_| |
|_|  |_|\___|\__, |\__,_|_.__/ \__,_|___/\__\___|_|  \__,_|
             |___/                                         
© Perpetrated by tonikelope since 2016
 */
package com.tonikelope.megabasterd;

import java.awt.event.KeyEvent;
import java.util.logging.Logger;

/**
 * @author tonikelope
 */
public class Get2FACode extends javax.swing.JDialog {

    private boolean _code_ok;

    private String _pin_code;

    private static final int MAX_CODE_LENGTH = 6;

    public boolean isCode_ok() {
        return this._code_ok;
    }

    public String getPin_code() {
        return this._pin_code;
    }

    public Get2FACode(final java.awt.Frame parent, final boolean modal, final String email, final MainPanel main_panel) {
        super(parent, modal);

        MiscTools.GUIRunAndWait(() -> {

            this.initComponents();

//            updateFonts(this, GUI_FONT, main_panel.getZoom_factor());

//            translateLabels(this);

            this._code_ok = false;

            this.email_label.setText(email);

            this.ok_button.setEnabled(false);

            this.pack();

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.cancel_button = new javax.swing.JButton();
        this.ok_button = new javax.swing.JButton();
        this.lock_label = new javax.swing.JLabel();
        this.email_label = new javax.swing.JLabel();
        this.status_label = new javax.swing.JLabel();
        this.please_label = new javax.swing.JLabel();
        this.current_code_textfield = new javax.swing.JTextField();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setTitle("2FA CODE");

        this.cancel_button.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        this.cancel_button.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/icons8-cancel-30.png"))); // NOI18N
        this.cancel_button.setText("CANCEL");
        this.cancel_button.setDoubleBuffered(true);
        this.cancel_button.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                Get2FACode.this.cancel_buttonActionPerformed(evt);
            }
        });

        this.ok_button.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        this.ok_button.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/icons8-ok-30.png"))); // NOI18N
        this.ok_button.setText("OK");
        this.ok_button.setDoubleBuffered(true);
        this.ok_button.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                Get2FACode.this.ok_buttonActionPerformed(evt);
            }
        });

        this.lock_label.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/lock_medium.png"))); // NOI18N
        this.lock_label.setDoubleBuffered(true);

        this.email_label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        this.email_label.setForeground(new java.awt.Color(255, 102, 0));
        this.email_label.setDoubleBuffered(true);

        this.status_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        this.status_label.setDoubleBuffered(true);

        this.please_label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        this.please_label.setText(LabelTranslatorSingleton.getInstance().translate("Please enter 2FA PIN CODE"));
        this.please_label.setDoubleBuffered(true);

        this.current_code_textfield.setBackground(new java.awt.Color(0, 153, 255));
        this.current_code_textfield.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        this.current_code_textfield.setForeground(new java.awt.Color(255, 255, 255));
        this.current_code_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        this.current_code_textfield.setDoubleBuffered(true);
        this.current_code_textfield.setMargin(new java.awt.Insets(2, 2, 2, 2));
        this.current_code_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(final java.awt.event.KeyEvent evt) {
                Get2FACode.this.current_code_textfieldKeyTyped(evt);
            }

            @Override
            public void keyPressed(final java.awt.event.KeyEvent evt) {
                Get2FACode.this.current_code_textfieldKeyPressed(evt);
            }

            @Override
            public void keyReleased(final java.awt.event.KeyEvent evt) {
                Get2FACode.this.current_code_textfieldKeyReleased(evt);
            }
        });

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
        this.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(this.status_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(this.ok_button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(this.cancel_button))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(this.lock_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(this.email_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(this.current_code_textfield)
                                                        .addComponent(this.please_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(this.email_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(this.please_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(this.current_code_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(this.lock_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(this.ok_button)
                                                .addComponent(this.cancel_button))
                                        .addComponent(this.status_label, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );

        this.pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_buttonActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed

        this._code_ok = false;

        this.setVisible(false);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void ok_buttonActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed

        this._code_ok = true;

        this._pin_code = this.current_code_textfield.getText();

        this.setVisible(false);
    }//GEN-LAST:event_ok_buttonActionPerformed

    private void current_code_textfieldKeyPressed(final java.awt.event.KeyEvent evt) {//GEN-FIRST:event_current_code_textfieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && this.ok_button.isEnabled()) {
            this.ok_buttonActionPerformed(null);
        }
    }//GEN-LAST:event_current_code_textfieldKeyPressed

    private void current_code_textfieldKeyTyped(final java.awt.event.KeyEvent evt) {//GEN-FIRST:event_current_code_textfieldKeyTyped

        if (this.current_code_textfield.getText().length() == MAX_CODE_LENGTH || (!Character.isDigit(evt.getKeyChar()) && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_current_code_textfieldKeyTyped

    private void current_code_textfieldKeyReleased(final java.awt.event.KeyEvent evt) {//GEN-FIRST:event_current_code_textfieldKeyReleased
        this.ok_button.setEnabled((this.current_code_textfield.getText().length() >= MAX_CODE_LENGTH));
    }//GEN-LAST:event_current_code_textfieldKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JTextField current_code_textfield;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel lock_label;
    private javax.swing.JButton ok_button;
    private javax.swing.JLabel please_label;
    private javax.swing.JLabel status_label;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(Get2FACode.class.getName());
}
