/*
 __  __                  _               _               _ 
|  \/  | ___  __ _  __ _| |__   __ _ ___| |_ ___ _ __ __| |
| |\/| |/ _ \/ _` |/ _` | '_ \ / _` / __| __/ _ \ '__/ _` |
| |  | |  __/ (_| | (_| | |_) | (_| \__ \ ||  __/ | | (_| |
|_|  |_|\___|\__, |\__,_|_.__/ \__,_|___/\__\___|_|  \__,_|
             |___/                                         
© Perpetrated by tonikelope since 2016
 */
package com.tonikelope.megabasterd;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

import static com.tonikelope.megabasterd.MainPanel.THREAD_POOL;
import static com.tonikelope.megabasterd.MiscTools.BASE642Bin;
import static com.tonikelope.megabasterd.MiscTools.Bin2BASE64;
import static com.tonikelope.megabasterd.MiscTools.HashBin;

/**
 * @author tonikelope
 */
public class SetMasterPasswordDialog extends javax.swing.JDialog {

    private boolean _pass_ok;

    private String _new_pass_hash;

    private byte[] _new_pass;

    private final String _salt;

    public boolean isPass_ok() {
        return this._pass_ok;
    }

    public byte[] getNew_pass() {
        return this._new_pass;
    }

    public void deleteNewPass() {

        if (this._new_pass != null) {

            Arrays.fill(this._new_pass, (byte) 0);
        }

        this._new_pass = null;
    }

    public String getNew_pass_hash() {
        return this._new_pass_hash;
    }

    /**
     * Creates new form MegaPassDialog
     */
    public SetMasterPasswordDialog(final java.awt.Frame parent, final boolean modal, final String salt, final MainPanel main_panel) {

        super(parent, modal);

        this._pass_ok = false;

        this._new_pass = null;

        this._new_pass_hash = null;

        this._salt = salt;

        MiscTools.GUIRunAndWait(() -> {

            this.initComponents();

//            updateFonts(this, GUI_FONT, main_panel.getZoom_factor());

//            translateLabels(this);

            this.pack();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.confirm_pass_textfield = new javax.swing.JPasswordField();
        this.confirm_pass_label = new javax.swing.JLabel();
        this.cancel_button = new javax.swing.JButton();
        this.ok_button = new javax.swing.JButton();
        this.lock_label = new javax.swing.JLabel();
        this.warning_label = new javax.swing.JLabel();
        this.new_pass_label = new javax.swing.JLabel();
        this.new_pass_textfield = new javax.swing.JPasswordField();
        this.status_label = new javax.swing.JLabel();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setTitle("Master password setup");
        this.setResizable(false);

        this.confirm_pass_textfield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        this.confirm_pass_textfield.setDoubleBuffered(true);
        this.confirm_pass_textfield.setMargin(new java.awt.Insets(2, 2, 2, 2));
        this.confirm_pass_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(final java.awt.event.KeyEvent evt) {
                SetMasterPasswordDialog.this.confirm_pass_textfieldKeyPressed(evt);
            }
        });

        this.confirm_pass_label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        this.confirm_pass_label.setText("Confirm new:");
        this.confirm_pass_label.setDoubleBuffered(true);

        this.cancel_button.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        this.cancel_button.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/icons8-cancel-30.png"))); // NOI18N
        this.cancel_button.setText("CANCEL");
        this.cancel_button.setDoubleBuffered(true);
        this.cancel_button.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                SetMasterPasswordDialog.this.cancel_buttonActionPerformed(evt);
            }
        });

        this.ok_button.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        this.ok_button.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/icons8-ok-30.png"))); // NOI18N
        this.ok_button.setText("OK");
        this.ok_button.setDoubleBuffered(true);
        this.ok_button.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                SetMasterPasswordDialog.this.ok_buttonActionPerformed(evt);
            }
        });

        this.lock_label.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/images/lock_medium.png"))); // NOI18N
        this.lock_label.setDoubleBuffered(true);

        this.warning_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        this.warning_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        this.warning_label.setText("WARNING: if you forget this password, you will have to insert all your accounts again.");
        this.warning_label.setDoubleBuffered(true);

        this.new_pass_label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        this.new_pass_label.setText("New pass:");
        this.new_pass_label.setDoubleBuffered(true);

        this.new_pass_textfield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        this.new_pass_textfield.setDoubleBuffered(true);
        this.new_pass_textfield.setMargin(new java.awt.Insets(2, 2, 2, 2));

        this.status_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        this.status_label.setDoubleBuffered(true);

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
        this.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(this.lock_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(this.confirm_pass_label)
                                                        .addComponent(this.new_pass_label))
                                                .addGap(15, 15, 15)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(this.confirm_pass_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                                                        .addComponent(this.new_pass_textfield))
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(this.warning_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(this.status_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGap(133, 133, 133))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(this.ok_button)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                                .addComponent(this.cancel_button)))
                                                .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(this.lock_label)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(this.new_pass_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(this.new_pass_label))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(this.confirm_pass_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(this.confirm_pass_label))))
                                .addGap(18, 18, 18)
                                .addComponent(this.warning_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(this.ok_button)
                                                .addComponent(this.cancel_button))
                                        .addComponent(this.status_label, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );

        this.pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_buttonActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void ok_buttonActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed

        this.status_label.setText(LabelTranslatorSingleton.getInstance().translate("Verifying your password, please wait..."));

        final Dialog tthis = this;

        THREAD_POOL.execute(() -> {
            try {
                if (Arrays.equals(this.new_pass_textfield.getPassword(), this.confirm_pass_textfield.getPassword())) {
                    MiscTools.GUIRun(() -> {
                        this.status_label.setText(LabelTranslatorSingleton.getInstance().translate("Processing your password, please wait..."));
                    });
                    if (this.new_pass_textfield.getPassword().length > 0) {

                        this._new_pass = CryptTools.PBKDF2HMACSHA256(new String(this.new_pass_textfield.getPassword()), BASE642Bin(this._salt), CryptTools.MASTER_PASSWORD_PBKDF2_ITERATIONS, CryptTools.MASTER_PASSWORD_PBKDF2_OUTPUT_BIT_LENGTH);

                        this._new_pass_hash = Bin2BASE64(HashBin("SHA-1", this._new_pass));
                    }
                    this._pass_ok = true;
                    MiscTools.GUIRun(() -> {
                        tthis.setVisible(false);
                    });
                } else {
                    MiscTools.GUIRun(() -> {
                        JOptionPane.showMessageDialog(tthis, LabelTranslatorSingleton.getInstance().translate("Passwords does not match!"), "Error", JOptionPane.ERROR_MESSAGE);

                        this.status_label.setText("");

                        this.new_pass_textfield.setText("");

                        this.confirm_pass_textfield.setText("");

                        this.new_pass_textfield.grabFocus();
                    });
                }
            } catch (final Exception ex) {
                LOG.log(Level.SEVERE, ex.getMessage());
            }
        });
    }//GEN-LAST:event_ok_buttonActionPerformed

    private void confirm_pass_textfieldKeyPressed(final java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirm_pass_textfieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.ok_buttonActionPerformed(null);
        }
    }//GEN-LAST:event_confirm_pass_textfieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel confirm_pass_label;
    private javax.swing.JPasswordField confirm_pass_textfield;
    private javax.swing.JLabel lock_label;
    private javax.swing.JLabel new_pass_label;
    private javax.swing.JPasswordField new_pass_textfield;
    private javax.swing.JButton ok_button;
    private javax.swing.JLabel status_label;
    private javax.swing.JLabel warning_label;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(SetMasterPasswordDialog.class.getName());
}
